import { TransitionItem } from './types';

export const BASIC_TRANSITIONS: TransitionItem[] = [
  {
    id: 'basic-1',
    name: 'Crossfade',
    category: 'basic',
    description: 'Smooth classic opacity crossfade between clips.',
    durationMs: 800,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p },
      toStyle: { opacity: p },
    }),
  },
  {
    id: 'basic-2',
    name: 'Fade to Black',
    category: 'basic',
    description: 'Fades outgoing clip to solid black before fading in next clip.',
    durationMs: 1000,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: Math.max(0, 1 - p * 2) },
      toStyle: { opacity: Math.max(0, (p - 0.5) * 2) },
      overlayStyle: { backgroundColor: '#000000', opacity: Math.sin(p * Math.PI) },
    }),
  },
  {
    id: 'basic-3',
    name: 'Fade to White',
    category: 'basic',
    description: 'Fades out into a bright white flash transition.',
    durationMs: 900,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: Math.max(0, 1 - p * 2) },
      toStyle: { opacity: Math.max(0, (p - 0.5) * 2) },
      overlayStyle: { backgroundColor: '#ffffff', opacity: Math.sin(p * Math.PI) },
    }),
  },
  {
    id: 'basic-4',
    name: 'Dip to Purple',
    category: 'basic',
    description: 'Smooth dip through deep royal purple.',
    durationMs: 850,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p },
      toStyle: { opacity: p },
      overlayStyle: { backgroundColor: '#5b21b6', opacity: Math.sin(p * Math.PI) * 0.8 },
    }),
  },
  {
    id: 'basic-5',
    name: 'Dip to Emerald',
    category: 'basic',
    description: 'Cinematic dip through vivid emerald green.',
    durationMs: 850,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p },
      toStyle: { opacity: p },
      overlayStyle: { backgroundColor: '#065f46', opacity: Math.sin(p * Math.PI) * 0.8 },
    }),
  },
  {
    id: 'basic-6',
    name: 'Dip to Crimson',
    category: 'basic',
    description: 'Dramatic dip through intense crimson red.',
    durationMs: 850,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p },
      toStyle: { opacity: p },
      overlayStyle: { backgroundColor: '#991b1b', opacity: Math.sin(p * Math.PI) * 0.8 },
    }),
  },
  {
    id: 'basic-7',
    name: 'Dip to Cyber Cyan',
    category: 'basic',
    description: 'Futuristic dip through bright neon cyan.',
    durationMs: 850,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p },
      toStyle: { opacity: p },
      overlayStyle: { backgroundColor: '#0891b2', opacity: Math.sin(p * Math.PI) * 0.8 },
    }),
  },
  {
    id: 'basic-8',
    name: 'Dip to Gold',
    category: 'basic',
    description: 'Luxurious dip through rich golden amber.',
    durationMs: 850,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p },
      toStyle: { opacity: p },
      overlayStyle: { backgroundColor: '#b45309', opacity: Math.sin(p * Math.PI) * 0.8 },
    }),
  },
  {
    id: 'basic-9',
    name: 'Blur Crossfade',
    category: 'basic',
    description: 'Blurs outgoing clip while fading into incoming clip.',
    durationMs: 900,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `blur(${p * 16}px)` },
      toStyle: { opacity: p, filter: `blur(${(1 - p) * 16}px)` },
    }),
  },
  {
    id: 'basic-10',
    name: 'Heavy Gaussian Dissolve',
    category: 'basic',
    description: 'Deep gaussian blur blended crossfade.',
    durationMs: 1000,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `blur(${p * 30}px)` },
      toStyle: { opacity: p, filter: `blur(${(1 - p) * 30}px)` },
    }),
  },
  {
    id: 'basic-11',
    name: 'Contrast Flash Blend',
    category: 'basic',
    description: 'High contrast flash peak mid-transition.',
    durationMs: 750,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `contrast(${100 + Math.sin(p * Math.PI) * 150}%)` },
      toStyle: { opacity: p, filter: `contrast(${100 + Math.sin(p * Math.PI) * 150}%)` },
    }),
  },
  {
    id: 'basic-12',
    name: 'Saturation Fade Peak',
    category: 'basic',
    description: 'Color saturates strongly during crossfade transition.',
    durationMs: 800,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `saturate(${100 + Math.sin(p * Math.PI) * 200}%)` },
      toStyle: { opacity: p, filter: `saturate(${100 + Math.sin(p * Math.PI) * 200}%)` },
    }),
  },
  {
    id: 'basic-13',
    name: 'Desaturate to Black & White',
    category: 'basic',
    description: 'Dips into black & white grayscale mid-way.',
    durationMs: 950,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `grayscale(${Math.sin(p * Math.PI) * 100}%)` },
      toStyle: { opacity: p, filter: `grayscale(${Math.sin(p * Math.PI) * 100}%)` },
    }),
  },
  {
    id: 'basic-14',
    name: 'Brightness Spike',
    category: 'basic',
    description: 'High exposure brightness flare across cuts.',
    durationMs: 700,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `brightness(${100 + Math.sin(p * Math.PI) * 180}%)` },
      toStyle: { opacity: p, filter: `brightness(${100 + Math.sin(p * Math.PI) * 180}%)` },
    }),
  },
  {
    id: 'basic-15',
    name: 'Underexposed Shadow Dip',
    category: 'basic',
    description: 'Dips scene brightness down to shadow levels.',
    durationMs: 900,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `brightness(${100 - Math.sin(p * Math.PI) * 80}%)` },
      toStyle: { opacity: p, filter: `brightness(${100 - Math.sin(p * Math.PI) * 80}%)` },
    }),
  },
  {
    id: 'basic-16',
    name: 'Sepia Vintage Blend',
    category: 'basic',
    description: 'Warms outgoing clip into antique sepia tone.',
    durationMs: 850,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `sepia(${Math.sin(p * Math.PI) * 90}%)` },
      toStyle: { opacity: p, filter: `sepia(${Math.sin(p * Math.PI) * 90}%)` },
    }),
  },
  {
    id: 'basic-17',
    name: 'Hue Rotation Blend',
    category: 'basic',
    description: 'Dynamic rainbow hue shift during crossfade.',
    durationMs: 900,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `hue-rotate(${p * 180}deg)` },
      toStyle: { opacity: p, filter: `hue-rotate(${(1 - p) * -180}deg)` },
    }),
  },
  {
    id: 'basic-18',
    name: 'Invert Color Flash',
    category: 'basic',
    description: 'Brief negative color invert burst on transition.',
    durationMs: 650,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `invert(${Math.sin(p * Math.PI) * 100}%)` },
      toStyle: { opacity: p, filter: `invert(${Math.sin(p * Math.PI) * 100}%)` },
    }),
  },
  {
    id: 'basic-19',
    name: 'Vignette Shadow Dissolve',
    category: 'basic',
    description: 'Circular dark vignette contracts around clip frame.',
    durationMs: 900,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p },
      toStyle: { opacity: p },
      overlayStyle: { boxShadow: `inset 0 0 ${Math.sin(p * Math.PI) * 150}px rgba(0,0,0,0.9)` },
    }),
  },
  {
    id: 'basic-20',
    name: 'Golden Vignette Flare',
    category: 'basic',
    description: 'Warm glowing golden vignette frame around cut.',
    durationMs: 900,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p },
      toStyle: { opacity: p },
      overlayStyle: { boxShadow: `inset 0 0 ${Math.sin(p * Math.PI) * 140}px rgba(245, 158, 11, 0.8)` },
    }),
  },
  {
    id: 'basic-21',
    name: 'Soft Luma Blend',
    category: 'basic',
    description: 'Soft lighting luminosity crossfade blend.',
    durationMs: 850,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `brightness(${100 + p * 40}%)` },
      toStyle: { opacity: p, filter: `brightness(${140 - p * 40}%)` },
    }),
  },
  {
    id: 'basic-22',
    name: 'Exposure Flare Dip',
    category: 'basic',
    description: 'Overexposed film camera flash mid-transition.',
    durationMs: 700,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `brightness(${100 + Math.sin(p * Math.PI) * 220}%) contrast(${100 + Math.sin(p * Math.PI) * 80}%)` },
      toStyle: { opacity: p, filter: `brightness(${100 + Math.sin(p * Math.PI) * 220}%) contrast(${100 + Math.sin(p * Math.PI) * 80}%)` },
    }),
  },
  {
    id: 'basic-23',
    name: 'Warm Sunset Glow',
    category: 'basic',
    description: 'Rich orange and golden hour sunset crossfade.',
    durationMs: 900,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `sepia(40%) hue-rotate(-15deg) saturate(160%)` },
      toStyle: { opacity: p, filter: `sepia(40%) hue-rotate(-15deg) saturate(160%)` },
      overlayStyle: { backgroundColor: '#ea580c', opacity: Math.sin(p * Math.PI) * 0.4 },
    }),
  },
  {
    id: 'basic-24',
    name: 'Cool Arctic Blue Dip',
    category: 'basic',
    description: 'Cool blue temperature shift during cut.',
    durationMs: 900,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `hue-rotate(180deg) saturate(140%)` },
      toStyle: { opacity: p, filter: `hue-rotate(180deg) saturate(140%)` },
      overlayStyle: { backgroundColor: '#0284c7', opacity: Math.sin(p * Math.PI) * 0.4 },
    }),
  },
  {
    id: 'basic-25',
    name: 'Neon Pink Glow Dip',
    category: 'basic',
    description: 'Vivid magenta glow overlay crossfade.',
    durationMs: 800,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p },
      toStyle: { opacity: p },
      overlayStyle: { backgroundColor: '#db2777', opacity: Math.sin(p * Math.PI) * 0.6 },
    }),
  },
  {
    id: 'basic-26',
    name: 'Pastel Bloom Dissolve',
    category: 'basic',
    description: 'Soft dreamy pastel light bloom between clips.',
    durationMs: 950,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `brightness(115%) blur(${p * 12}px)` },
      toStyle: { opacity: p, filter: `brightness(115%) blur(${(1 - p) * 12}px)` },
    }),
  },
  {
    id: 'basic-27',
    name: 'High Contrast Monochromatic',
    category: 'basic',
    description: 'Stark black and white contrast transition.',
    durationMs: 850,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `grayscale(100%) contrast(180%)` },
      toStyle: { opacity: p, filter: `grayscale(100%) contrast(180%)` },
    }),
  },
  {
    id: 'basic-28',
    name: 'Color Bleed Dip',
    category: 'basic',
    description: 'Intense color saturation bleed on cut.',
    durationMs: 800,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `saturate(${100 + Math.sin(p * Math.PI) * 300}%)` },
      toStyle: { opacity: p, filter: `saturate(${100 + Math.sin(p * Math.PI) * 300}%)` },
    }),
  },
  {
    id: 'basic-29',
    name: 'Solarize Glow Blend',
    category: 'basic',
    description: 'Solarized highlight inversion peak.',
    durationMs: 800,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `invert(${Math.sin(p * Math.PI) * 50}%) contrast(140%)` },
      toStyle: { opacity: p, filter: `invert(${Math.sin(p * Math.PI) * 50}%) contrast(140%)` },
    }),
  },
  {
    id: 'basic-30',
    name: 'Thermal Heat Shift',
    category: 'basic',
    description: 'Thermal camera color palette shift.',
    durationMs: 850,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `hue-rotate(${Math.sin(p * Math.PI) * 120}deg) saturate(250%)` },
      toStyle: { opacity: p, filter: `hue-rotate(${Math.sin(p * Math.PI) * 120}deg) saturate(250%)` },
    }),
  },
  {
    id: 'basic-31',
    name: 'Night Vision Green Flash',
    category: 'basic',
    description: 'Phosphor green night vision camera dip.',
    durationMs: 800,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p },
      toStyle: { opacity: p },
      overlayStyle: { backgroundColor: '#15803d', opacity: Math.sin(p * Math.PI) * 0.7 },
    }),
  },
  {
    id: 'basic-32',
    name: 'Cyanotype Blue Blend',
    category: 'basic',
    description: 'Deep prussian blue monochrome print blend.',
    durationMs: 900,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `hue-rotate(190deg) sepia(60%)` },
      toStyle: { opacity: p, filter: `hue-rotate(190deg) sepia(60%)` },
    }),
  },
  {
    id: 'basic-33',
    name: 'High Key White Fade',
    category: 'basic',
    description: 'Overexposed high-key lighting dissolve.',
    durationMs: 850,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `brightness(${100 + p * 100}%)` },
      toStyle: { opacity: p, filter: `brightness(${200 - p * 100}%)` },
    }),
  },
  {
    id: 'basic-34',
    name: 'Low Key Shadow Dip',
    category: 'basic',
    description: 'Dark moody low-key lighting shadow dip.',
    durationMs: 900,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `brightness(${100 - p * 90}%)` },
      toStyle: { opacity: p, filter: `brightness(${10 + p * 90}%)` },
    }),
  },
  {
    id: 'basic-35',
    name: 'Duotone Violet Gold',
    category: 'basic',
    description: 'Dual tone violet and gold overlay crossfade.',
    durationMs: 900,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p },
      toStyle: { opacity: p },
      overlayStyle: { backgroundColor: '#7e22ce', opacity: Math.sin(p * Math.PI) * 0.5 },
    }),
  },
  {
    id: 'basic-36',
    name: 'Electric Magenta Pulse',
    category: 'basic',
    description: 'High energy magenta color pulse cut.',
    durationMs: 700,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `hue-rotate(300deg) saturate(200%)` },
      toStyle: { opacity: p, filter: `hue-rotate(300deg) saturate(200%)` },
    }),
  },
  {
    id: 'basic-37',
    name: 'Teal & Orange Grade Shift',
    category: 'basic',
    description: 'Classic Hollywood teal & orange contrast shift.',
    durationMs: 900,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `contrast(130%) saturate(150%) hue-rotate(-10deg)` },
      toStyle: { opacity: p, filter: `contrast(130%) saturate(150%) hue-rotate(-10deg)` },
    }),
  },
  {
    id: 'basic-38',
    name: 'Film Grain Crossfade',
    category: 'basic',
    description: 'Textured analog film grain blended transition.',
    durationMs: 950,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `contrast(115%) sepia(20%)` },
      toStyle: { opacity: p, filter: `contrast(115%) sepia(20%)` },
      overlayStyle: { backgroundImage: 'radial-gradient(rgba(255,255,255,0.1) 1px, transparent 0)', backgroundSize: '4px 4px', opacity: Math.sin(p * Math.PI) },
    }),
  },
  {
    id: 'basic-39',
    name: 'Velvet Midnight Black',
    category: 'basic',
    description: 'Deep velvet black fade with smooth curve.',
    durationMs: 1000,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: Math.cos(p * Math.PI * 0.5) },
      toStyle: { opacity: Math.sin(p * Math.PI * 0.5) },
      overlayStyle: { backgroundColor: '#09090b', opacity: Math.sin(p * Math.PI) },
    }),
  },
  {
    id: 'basic-40',
    name: 'Soft Focus Radial Blur',
    category: 'basic',
    description: 'Soft lens focus blur fade out into clip.',
    durationMs: 900,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `blur(${p * 20}px) brightness(${100 + p * 20}%)` },
      toStyle: { opacity: p, filter: `blur(${(1 - p) * 20}px) brightness(${120 - p * 20}%)` },
    }),
  },
  {
    id: 'basic-41',
    name: 'Dip to Deep Purple',
    category: 'basic',
    description: 'Rich dark violet color dip between scenes.',
    durationMs: 850,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p },
      toStyle: { opacity: p },
      overlayStyle: { backgroundColor: '#3b0764', opacity: Math.sin(p * Math.PI) },
    }),
  },
  {
    id: 'basic-42',
    name: 'Dip to Sunset Red',
    category: 'basic',
    description: 'Vivid red-orange twilight horizon dip.',
    durationMs: 850,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p },
      toStyle: { opacity: p },
      overlayStyle: { backgroundColor: '#c2410c', opacity: Math.sin(p * Math.PI) },
    }),
  },
  {
    id: 'basic-43',
    name: 'Dip to Mint Green',
    category: 'basic',
    description: 'Refreshing pastel mint green color dip.',
    durationMs: 850,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p },
      toStyle: { opacity: p },
      overlayStyle: { backgroundColor: '#0d9488', opacity: Math.sin(p * Math.PI) },
    }),
  },
  {
    id: 'basic-44',
    name: 'Exposure Bloom Flash',
    category: 'basic',
    description: 'Bright optical lens bloom exposure burst.',
    durationMs: 700,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `brightness(${100 + Math.sin(p * Math.PI) * 250}%) blur(${Math.sin(p * Math.PI) * 8}px)` },
      toStyle: { opacity: p, filter: `brightness(${100 + Math.sin(p * Math.PI) * 250}%) blur(${Math.sin(p * Math.PI) * 8}px)` },
    }),
  },
  {
    id: 'basic-45',
    name: 'Negative Color Dip',
    category: 'basic',
    description: 'Full inverted negative film flash dip.',
    durationMs: 650,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `invert(${Math.sin(p * Math.PI) * 100}%)` },
      toStyle: { opacity: p, filter: `invert(${Math.sin(p * Math.PI) * 100}%)` },
    }),
  },
  {
    id: 'basic-46',
    name: 'Warm Amber Film Wash',
    category: 'basic',
    description: 'Warm analog film stock color wash.',
    durationMs: 900,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `sepia(50%) saturate(140%)` },
      toStyle: { opacity: p, filter: `sepia(50%) saturate(140%)` },
      overlayStyle: { backgroundColor: '#d97706', opacity: Math.sin(p * Math.PI) * 0.35 },
    }),
  },
  {
    id: 'basic-47',
    name: 'Cool Slate Grey Dip',
    category: 'basic',
    description: 'Minimalist slate grey tone dip.',
    durationMs: 850,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p },
      toStyle: { opacity: p },
      overlayStyle: { backgroundColor: '#334155', opacity: Math.sin(p * Math.PI) * 0.8 },
    }),
  },
  {
    id: 'basic-48',
    name: 'Prism Rainbow Flash',
    category: 'basic',
    description: 'Reflective prism rainbow hue burst.',
    durationMs: 800,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `hue-rotate(${p * 360}deg) saturate(220%)` },
      toStyle: { opacity: p, filter: `hue-rotate(${p * 360}deg) saturate(220%)` },
    }),
  },
  {
    id: 'basic-49',
    name: 'Soft Diffusion Glow',
    category: 'basic',
    description: 'Soft lighting diffusion filter crossfade.',
    durationMs: 950,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `blur(${p * 10}px) contrast(90%)` },
      toStyle: { opacity: p, filter: `blur(${(1 - p) * 10}px) contrast(90%)` },
    }),
  },
  {
    id: 'basic-50',
    name: 'Master Cinema Crossfade',
    category: 'basic',
    description: 'Ultimate smooth theatrical cinema crossfade.',
    durationMs: 1000,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, filter: `contrast(${100 + Math.sin(p * Math.PI) * 15}%)` },
      toStyle: { opacity: p, filter: `contrast(${100 + Math.sin(p * Math.PI) * 15}%)` },
    }),
  },
];
