import { TransitionItem } from './types';

export const SWIPE_TRANSITIONS: TransitionItem[] = [
  {
    id: 'swipe-1',
    name: 'Swipe Left',
    category: 'swipe',
    description: 'Smooth directional horizontal swipe to the left.',
    durationMs: 750,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p * 0.3, transform: `translateX(${-p * 100}%)` },
      toStyle: { opacity: 0.7 + p * 0.3, transform: `translateX(${(1 - p) * 100}%)` },
    }),
  },
  {
    id: 'swipe-2',
    name: 'Swipe Right',
    category: 'swipe',
    description: 'Smooth directional horizontal swipe to the right.',
    durationMs: 750,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p * 0.3, transform: `translateX(${p * 100}%)` },
      toStyle: { opacity: 0.7 + p * 0.3, transform: `translateX(${(p - 1) * 100}%)` },
    }),
  },
  {
    id: 'swipe-3',
    name: 'Swipe Up',
    category: 'swipe',
    description: 'Vertical ascending swipe upward into next scene.',
    durationMs: 750,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p * 0.3, transform: `translateY(${-p * 100}%)` },
      toStyle: { opacity: 0.7 + p * 0.3, transform: `translateY(${(1 - p) * 100}%)` },
    }),
  },
  {
    id: 'swipe-4',
    name: 'Swipe Down',
    category: 'swipe',
    description: 'Vertical descending swipe downward into next scene.',
    durationMs: 750,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p * 0.3, transform: `translateY(${p * 100}%)` },
      toStyle: { opacity: 0.7 + p * 0.3, transform: `translateY(${(p - 1) * 100}%)` },
    }),
  },
  {
    id: 'swipe-5',
    name: 'Whip Pan Left',
    category: 'swipe',
    description: 'Fast action camera whip pan move to the left.',
    durationMs: 650,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, transform: `translateX(${-p * 100}%)`, filter: `blur(${p * 20}px)` },
      toStyle: { opacity: p, transform: `translateX(${(1 - p) * 100}%)`, filter: `blur(${(1 - p) * 20}px)` },
    }),
  },
  {
    id: 'swipe-6',
    name: 'Whip Pan Right',
    category: 'swipe',
    description: 'Fast action camera whip pan move to the right.',
    durationMs: 650,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, transform: `translateX(${p * 100}%)`, filter: `blur(${p * 20}px)` },
      toStyle: { opacity: p, transform: `translateX(${(p - 1) * 100}%)`, filter: `blur(${(1 - p) * 20}px)` },
    }),
  },
  {
    id: 'swipe-7',
    name: 'Whip Pan Up',
    category: 'swipe',
    description: 'Fast vertical whip camera tilt moving upward.',
    durationMs: 650,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, transform: `translateY(${-p * 100}%)`, filter: `blur(${p * 20}px)` },
      toStyle: { opacity: p, transform: `translateY(${(1 - p) * 100}%)`, filter: `blur(${(1 - p) * 20}px)` },
    }),
  },
  {
    id: 'swipe-8',
    name: 'Whip Pan Down',
    category: 'swipe',
    description: 'Fast vertical whip camera tilt moving downward.',
    durationMs: 650,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, transform: `translateY(${p * 100}%)`, filter: `blur(${p * 20}px)` },
      toStyle: { opacity: p, transform: `translateY(${(p - 1) * 100}%)`, filter: `blur(${(1 - p) * 20}px)` },
    }),
  },
  {
    id: 'swipe-9',
    name: 'Diagonal Swipe Top-Left',
    category: 'swipe',
    description: 'Diagonal angled swipe toward top-left corner.',
    durationMs: 800,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p * 0.3, transform: `translate(${-p * 100}%, ${-p * 100}%)` },
      toStyle: { opacity: 0.7 + p * 0.3, transform: `translate(${(1 - p) * 100}%, ${(1 - p) * 100}%)` },
    }),
  },
  {
    id: 'swipe-10',
    name: 'Diagonal Swipe Top-Right',
    category: 'swipe',
    description: 'Diagonal angled swipe toward top-right corner.',
    durationMs: 800,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p * 0.3, transform: `translate(${p * 100}%, ${-p * 100}%)` },
      toStyle: { opacity: 0.7 + p * 0.3, transform: `translate(${(p - 1) * 100}%, ${(1 - p) * 100}%)` },
    }),
  },
  {
    id: 'swipe-11',
    name: 'Diagonal Swipe Bottom-Left',
    category: 'swipe',
    description: 'Diagonal angled swipe toward bottom-left corner.',
    durationMs: 800,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p * 0.3, transform: `translate(${-p * 100}%, ${p * 100}%)` },
      toStyle: { opacity: 0.7 + p * 0.3, transform: `translate(${(1 - p) * 100}%, ${(p - 1) * 100}%)` },
    }),
  },
  {
    id: 'swipe-12',
    name: 'Diagonal Swipe Bottom-Right',
    category: 'swipe',
    description: 'Diagonal angled swipe toward bottom-right corner.',
    durationMs: 800,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p * 0.3, transform: `translate(${p * 100}%, ${p * 100}%)` },
      toStyle: { opacity: 0.7 + p * 0.3, transform: `translate(${(p - 1) * 100}%, ${(p - 1) * 100}%)` },
    }),
  },
  {
    id: 'swipe-13',
    name: 'Spin Swipe Left',
    category: 'swipe',
    description: 'Rotating horizontal swipe movement to the left.',
    durationMs: 850,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, transform: `translateX(${-p * 100}%) rotate(${-p * 45}deg)` },
      toStyle: { opacity: p, transform: `translateX(${(1 - p) * 100}%) rotate(${(1 - p) * 45}deg)` },
    }),
  },
  {
    id: 'swipe-14',
    name: 'Spin Swipe Right',
    category: 'swipe',
    description: 'Rotating horizontal swipe movement to the right.',
    durationMs: 850,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, transform: `translateX(${p * 100}%) rotate(${p * 45}deg)` },
      toStyle: { opacity: p, transform: `translateX(${(p - 1) * 100}%) rotate(${(p - 1) * 45}deg)` },
    }),
  },
  {
    id: 'swipe-15',
    name: 'Push Left',
    category: 'swipe',
    description: 'Incoming clip physically pushes outgoing clip left.',
    durationMs: 750,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { transform: `translateX(${-p * 100}%)` },
      toStyle: { transform: `translateX(${(1 - p) * 100}%)` },
    }),
  },
  {
    id: 'swipe-16',
    name: 'Push Right',
    category: 'swipe',
    description: 'Incoming clip physically pushes outgoing clip right.',
    durationMs: 750,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { transform: `translateX(${p * 100}%)` },
      toStyle: { transform: `translateX(${(p - 1) * 100}%)` },
    }),
  },
  {
    id: 'swipe-17',
    name: 'Push Up',
    category: 'swipe',
    description: 'Incoming clip physically pushes outgoing clip up.',
    durationMs: 750,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { transform: `translateY(${-p * 100}%)` },
      toStyle: { transform: `translateY(${(1 - p) * 100}%)` },
    }),
  },
  {
    id: 'swipe-18',
    name: 'Push Down',
    category: 'swipe',
    description: 'Incoming clip physically pushes outgoing clip down.',
    durationMs: 750,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { transform: `translateY(${p * 100}%)` },
      toStyle: { transform: `translateY(${(p - 1) * 100}%)` },
    }),
  },
  {
    id: 'swipe-19',
    name: 'Cover Left Overlay',
    category: 'swipe',
    description: 'New clip slides over static outgoing clip from right to left.',
    durationMs: 750,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 },
      toStyle: { opacity: 1, transform: `translateX(${(1 - p) * 100}%)` },
    }),
  },
  {
    id: 'swipe-20',
    name: 'Cover Right Overlay',
    category: 'swipe',
    description: 'New clip slides over static outgoing clip from left to right.',
    durationMs: 750,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 },
      toStyle: { opacity: 1, transform: `translateX(${(p - 1) * 100}%)` },
    }),
  },
  {
    id: 'swipe-21',
    name: 'Cover Up Overlay',
    category: 'swipe',
    description: 'New clip slides upward over static outgoing clip.',
    durationMs: 750,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 },
      toStyle: { opacity: 1, transform: `translateY(${(1 - p) * 100}%)` },
    }),
  },
  {
    id: 'swipe-22',
    name: 'Cover Down Overlay',
    category: 'swipe',
    description: 'New clip slides downward over static outgoing clip.',
    durationMs: 750,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 },
      toStyle: { opacity: 1, transform: `translateY(${(p - 1) * 100}%)` },
    }),
  },
  {
    id: 'swipe-23',
    name: 'Reveal Left',
    category: 'swipe',
    description: 'Outgoing clip slides left revealing static new clip behind.',
    durationMs: 750,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1, transform: `translateX(${-p * 100}%)` },
      toStyle: { opacity: 1 },
    }),
  },
  {
    id: 'swipe-24',
    name: 'Reveal Right',
    category: 'swipe',
    description: 'Outgoing clip slides right revealing static new clip behind.',
    durationMs: 750,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1, transform: `translateX(${p * 100}%)` },
      toStyle: { opacity: 1 },
    }),
  },
  {
    id: 'swipe-25',
    name: 'Reveal Up',
    category: 'swipe',
    description: 'Outgoing clip slides upward revealing static new clip.',
    durationMs: 750,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1, transform: `translateY(${-p * 100}%)` },
      toStyle: { opacity: 1 },
    }),
  },
  {
    id: 'swipe-26',
    name: 'Reveal Down',
    category: 'swipe',
    description: 'Outgoing clip slides downward revealing static new clip.',
    durationMs: 750,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1, transform: `translateY(${p * 100}%)` },
      toStyle: { opacity: 1 },
    }),
  },
  {
    id: 'swipe-27',
    name: 'Split Vertical Out',
    category: 'swipe',
    description: 'Screen splits vertically in center sliding open.',
    durationMs: 850,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, transform: `scaleX(${1 - p})` },
      toStyle: { opacity: p, transform: `scaleX(${p})` },
    }),
  },
  {
    id: 'swipe-28',
    name: 'Split Horizontal Out',
    category: 'swipe',
    description: 'Screen splits horizontally in center sliding open.',
    durationMs: 850,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, transform: `scaleY(${1 - p})` },
      toStyle: { opacity: p, transform: `scaleY(${p})` },
    }),
  },
  {
    id: 'swipe-29',
    name: 'Elastic Push Left',
    category: 'swipe',
    description: 'Elastic spring bounce push transition to left.',
    durationMs: 800,
    renderOverlayStyle: (p: number) => {
      const elastic = Math.sin(p * Math.PI * 2) * 10;
      return {
        fromStyle: { transform: `translateX(${-p * 100 + elastic}%)` },
        toStyle: { transform: `translateX(${(1 - p) * 100 + elastic}%)` },
      };
    },
  },
  {
    id: 'swipe-30',
    name: 'Elastic Push Right',
    category: 'swipe',
    description: 'Elastic spring bounce push transition to right.',
    durationMs: 800,
    renderOverlayStyle: (p: number) => {
      const elastic = Math.sin(p * Math.PI * 2) * 10;
      return {
        fromStyle: { transform: `translateX(${p * 100 + elastic}%)` },
        toStyle: { transform: `translateX(${(p - 1) * 100 + elastic}%)` },
      };
    },
  },
  {
    id: 'swipe-31',
    name: 'Parallax Slide Left',
    category: 'swipe',
    description: 'Multi-speed depth layer parallax slide left.',
    durationMs: 850,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, transform: `translateX(${-p * 120}%) scale(0.9)` },
      toStyle: { opacity: p, transform: `translateX(${(1 - p) * 80}%) scale(1)` },
    }),
  },
  {
    id: 'swipe-32',
    name: 'Parallax Slide Right',
    category: 'swipe',
    description: 'Multi-speed depth layer parallax slide right.',
    durationMs: 850,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, transform: `translateX(${p * 120}%) scale(0.9)` },
      toStyle: { opacity: p, transform: `translateX(${(p - 1) * 80}%) scale(1)` },
    }),
  },
  {
    id: 'swipe-33',
    name: '3D Perspective Door Left',
    category: 'swipe',
    description: '3D perspective door opening slide left.',
    durationMs: 900,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, transform: `perspective(800px) rotateY(${-p * 60}deg) translateX(${-p * 50}%)` },
      toStyle: { opacity: p, transform: `perspective(800px) rotateY(${(1 - p) * 60}deg) translateX(${(1 - p) * 50}%)` },
    }),
  },
  {
    id: 'swipe-34',
    name: '3D Perspective Door Right',
    category: 'swipe',
    description: '3D perspective door opening slide right.',
    durationMs: 900,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, transform: `perspective(800px) rotateY(${p * 60}deg) translateX(${p * 50}%)` },
      toStyle: { opacity: p, transform: `perspective(800px) rotateY(${(p - 1) * 60}deg) translateX(${(p - 1) * 50}%)` },
    }),
  },
  {
    id: 'swipe-35',
    name: '3D Cube Turn Left',
    category: 'swipe',
    description: '3D cube side rotation to left.',
    durationMs: 900,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, transform: `perspective(1000px) rotateY(${-p * 90}deg)` },
      toStyle: { opacity: p, transform: `perspective(1000px) rotateY(${(1 - p) * 90}deg)` },
    }),
  },
  {
    id: 'swipe-36',
    name: '3D Cube Turn Right',
    category: 'swipe',
    description: '3D cube side rotation to right.',
    durationMs: 900,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, transform: `perspective(1000px) rotateY(${p * 90}deg)` },
      toStyle: { opacity: p, transform: `perspective(1000px) rotateY(${(p - 1) * 90}deg)` },
    }),
  },
  {
    id: 'swipe-37',
    name: 'Glitch Whip Swipe Left',
    category: 'swipe',
    description: 'Digital video glitch horizontal whip left.',
    durationMs: 700,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, transform: `translateX(${-p * 100}%) skewX(${Math.sin(p * 15) * 15}deg)`, filter: `blur(${p * 10}px)` },
      toStyle: { opacity: p, transform: `translateX(${(1 - p) * 100}%) skewX(${Math.sin(p * 15) * -15}deg)` },
    }),
  },
  {
    id: 'swipe-38',
    name: 'Glitch Whip Swipe Right',
    category: 'swipe',
    description: 'Digital video glitch horizontal whip right.',
    durationMs: 700,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, transform: `translateX(${p * 100}%) skewX(${Math.sin(p * 15) * -15}deg)`, filter: `blur(${p * 10}px)` },
      toStyle: { opacity: p, transform: `translateX(${(p - 1) * 100}%) skewX(${Math.sin(p * 15) * 15}deg)` },
    }),
  },
  {
    id: 'swipe-39',
    name: 'RGB Split Whip Swipe',
    category: 'swipe',
    description: 'Chromatic RGB color fringe whip swipe.',
    durationMs: 750,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, transform: `translateX(${-p * 100}%)`, filter: `drop-shadow(${p * 15}px 0 red) drop-shadow(${-p * 15}px 0 blue)` },
      toStyle: { opacity: p, transform: `translateX(${(1 - p) * 100}%)` },
    }),
  },
  {
    id: 'swipe-40',
    name: 'Fast Action Speed Swipe Left',
    category: 'swipe',
    description: 'Ultra fast action movie directional speed swipe.',
    durationMs: 550,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, transform: `translateX(${-p * 100}%)`, filter: `blur(${p * 30}px)` },
      toStyle: { opacity: p, transform: `translateX(${(1 - p) * 100}%)`, filter: `blur(${(1 - p) * 30}px)` },
    }),
  },
  {
    id: 'swipe-41',
    name: 'Fast Action Speed Swipe Right',
    category: 'swipe',
    description: 'Ultra fast action movie directional speed right swipe.',
    durationMs: 550,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, transform: `translateX(${p * 100}%)`, filter: `blur(${p * 30}px)` },
      toStyle: { opacity: p, transform: `translateX(${(p - 1) * 100}%)`, filter: `blur(${(1 - p) * 30}px)` },
    }),
  },
  {
    id: 'swipe-42',
    name: 'Slow Cinema Glide Left',
    category: 'swipe',
    description: 'Gentle slow pan glide transition to the left.',
    durationMs: 1100,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p * 0.2, transform: `translateX(${-p * 100}%)` },
      toStyle: { opacity: 0.8 + p * 0.2, transform: `translateX(${(1 - p) * 100}%)` },
    }),
  },
  {
    id: 'swipe-43',
    name: 'Slow Cinema Glide Right',
    category: 'swipe',
    description: 'Gentle slow pan glide transition to the right.',
    durationMs: 1100,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p * 0.2, transform: `translateX(${p * 100}%)` },
      toStyle: { opacity: 0.8 + p * 0.2, transform: `translateX(${(p - 1) * 100}%)` },
    }),
  },
  {
    id: 'swipe-44',
    name: 'Corner Push Top-Left',
    category: 'swipe',
    description: 'Push transition entering from top-left corner.',
    durationMs: 800,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { transform: `translate(${-p * 100}%, ${-p * 100}%)` },
      toStyle: { transform: `translate(${(1 - p) * 100}%, ${(1 - p) * 100}%)` },
    }),
  },
  {
    id: 'swipe-45',
    name: 'Corner Push Top-Right',
    category: 'swipe',
    description: 'Push transition entering from top-right corner.',
    durationMs: 800,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { transform: `translate(${p * 100}%, ${-p * 100}%)` },
      toStyle: { transform: `translate(${(p - 1) * 100}%, ${(1 - p) * 100}%)` },
    }),
  },
  {
    id: 'swipe-46',
    name: 'Corner Push Bottom-Left',
    category: 'swipe',
    description: 'Push transition entering from bottom-left corner.',
    durationMs: 800,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { transform: `translate(${-p * 100}%, ${p * 100}%)` },
      toStyle: { transform: `translate(${(1 - p) * 100}%, ${(p - 1) * 100}%)` },
    }),
  },
  {
    id: 'swipe-47',
    name: 'Corner Push Bottom-Right',
    category: 'swipe',
    description: 'Push transition entering from bottom-right corner.',
    durationMs: 800,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { transform: `translate(${p * 100}%, ${p * 100}%)` },
      toStyle: { transform: `translate(${(p - 1) * 100}%, ${(p - 1) * 100}%)` },
    }),
  },
  {
    id: 'swipe-48',
    name: 'Vignette Dark Swipe Left',
    category: 'swipe',
    description: 'Dark edge vignette swipe movement left.',
    durationMs: 850,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, transform: `translateX(${-p * 100}%)` },
      toStyle: { opacity: p, transform: `translateX(${(1 - p) * 100}%)` },
      overlayStyle: { boxShadow: `inset 0 0 ${Math.sin(p * Math.PI) * 100}px rgba(0,0,0,0.8)` },
    }),
  },
  {
    id: 'swipe-49',
    name: 'Gold Light Leak Swipe',
    category: 'swipe',
    description: 'Golden hour optical light leak whip swipe.',
    durationMs: 800,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, transform: `translateX(${-p * 100}%)` },
      toStyle: { opacity: p, transform: `translateX(${(1 - p) * 100}%)` },
      overlayStyle: { backgroundColor: '#f59e0b', opacity: Math.sin(p * Math.PI) * 0.4 },
    }),
  },
  {
    id: 'swipe-50',
    name: 'Master Cinema Whip Swipe',
    category: 'swipe',
    description: 'Ultimate master cinema optical whip pan swipe.',
    durationMs: 900,
    renderOverlayStyle: (p: number) => ({
      fromStyle: { opacity: 1 - p, transform: `translateX(${-p * 100}%)`, filter: `blur(${p * 15}px) contrast(110%)` },
      toStyle: { opacity: p, transform: `translateX(${(1 - p) * 100}%)`, filter: `blur(${(1 - p) * 15}px) contrast(110%)` },
    }),
  },
];
