import { VideoEffect } from './types';

export const CINEMATIC_EFFECTS: VideoEffect[] = [
  {
    id: 'cine-1',
    name: 'Teal & Orange',
    category: 'cinematic',
    description: 'Iconic Hollywood blockbuster color grade with rich teals and warm skin tones.',
    filterCss: 'contrast(115%) saturate(130%) hue-rotate(-10deg)',
    overlayStyle: {
      background: 'radial-gradient(circle, rgba(255,140,0,0.08) 0%, rgba(0,128,128,0.15) 100%)',
      mixBlendMode: 'color-dodge',
    },
  },
  {
    id: 'cine-2',
    name: 'Blockbuster Gold',
    category: 'cinematic',
    description: 'Warm golden highlight grade with high contrast shadows.',
    filterCss: 'contrast(120%) brightness(105%) sepia(30%) hue-rotate(-15deg)',
  },
  {
    id: 'cine-3',
    name: 'Cyberpunk Neon',
    category: 'cinematic',
    description: 'Futuristic neon lighting with electric purple and cyan glow.',
    filterCss: 'contrast(130%) saturate(160%) hue-rotate(140deg)',
    overlayStyle: {
      background: 'linear-gradient(135deg, rgba(236,72,153,0.15), rgba(6,182,212,0.15))',
      mixBlendMode: 'screen',
    },
  },
  {
    id: 'cine-4',
    name: 'Film Noir B&W',
    category: 'cinematic',
    description: 'High-contrast monochrome classic noir film look.',
    filterCss: 'grayscale(100%) contrast(145%) brightness(95%)',
    overlayStyle: {
      boxShadow: 'inset 0 0 100px rgba(0,0,0,0.8)',
    },
  },
  {
    id: 'cine-5',
    name: 'Bleach Bypass',
    category: 'cinematic',
    description: 'Silver halide retention look with desaturated colors and intense contrast.',
    filterCss: 'contrast(140%) saturate(60%) brightness(102%)',
  },
  {
    id: 'cine-6',
    name: 'Anamorphic Blue Flare',
    category: 'cinematic',
    description: 'Wide anamorphic lens streak with cool horizontal flares.',
    filterCss: 'contrast(110%) saturate(120%)',
    overlayStyle: {
      background: 'linear-gradient(180deg, transparent 45%, rgba(59,130,246,0.2) 50%, transparent 55%)',
      mixBlendMode: 'screen',
    },
  },
  {
    id: 'cine-7',
    name: 'Cold Thriller',
    category: 'cinematic',
    description: 'Chilly desaturated blue and green tones for suspenseful drama.',
    filterCss: 'contrast(115%) saturate(75%) hue-rotate(80deg) brightness(96%)',
  },
  {
    id: 'cine-8',
    name: 'Sunset Warmth',
    category: 'cinematic',
    description: 'Deep crimson and golden orange sunset illumination.',
    filterCss: 'contrast(110%) saturate(140%) sepia(25%) hue-rotate(-20deg)',
    overlayStyle: {
      background: 'linear-gradient(to top, rgba(239,68,68,0.12), rgba(245,158,11,0.08))',
    },
  },
  {
    id: 'cine-9',
    name: 'Moody Vignette',
    category: 'cinematic',
    description: 'Darkened borders emphasizing central focal area.',
    filterCss: 'contrast(112%) brightness(98%)',
    overlayStyle: {
      boxShadow: 'inset 0 0 120px rgba(0,0,0,0.85)',
    },
  },
  {
    id: 'cine-10',
    name: 'Sci-Fi Cyan',
    category: 'cinematic',
    description: 'Futuristic sci-fi green and cyan matrix style palette.',
    filterCss: 'contrast(125%) saturate(135%) hue-rotate(90deg)',
  },
  {
    id: 'cine-11',
    name: 'Golden Hour Glow',
    category: 'cinematic',
    description: 'Soft warm magic hour daylight enhancement.',
    filterCss: 'contrast(105%) brightness(108%) sepia(20%) saturate(125%)',
  },
  {
    id: 'cine-12',
    name: 'Emerald Matrix',
    category: 'cinematic',
    description: 'Deep green shadows with punchy matrix highlight tones.',
    filterCss: 'contrast(130%) saturate(110%) hue-rotate(60deg) brightness(94%)',
  },
  {
    id: 'cine-13',
    name: 'Cross Processed Film',
    category: 'cinematic',
    description: 'Experimental chemical processing color shift look.',
    filterCss: 'contrast(135%) saturate(150%) hue-rotate(30deg)',
  },
  {
    id: 'cine-14',
    name: 'Dramatic Shadow Shift',
    category: 'cinematic',
    description: 'Crushed deep blacks with crisp highlight dynamic range.',
    filterCss: 'contrast(150%) brightness(92%) saturate(110%)',
  },
  {
    id: 'cine-15',
    name: 'Pastel Dream',
    category: 'cinematic',
    description: 'Soft muted pastel palette with gentle bloom lighting.',
    filterCss: 'brightness(110%) contrast(92%) saturate(85%)',
    overlayStyle: {
      background: 'rgba(255,255,255,0.05)',
      mixBlendMode: 'soft-light',
    },
  },
  {
    id: 'cine-16',
    name: 'Warm Vintage Film',
    category: 'cinematic',
    description: 'Nostalgic 1970s cinema color stock warmth.',
    filterCss: 'contrast(108%) sepia(35%) saturate(115%) brightness(102%)',
  },
  {
    id: 'cine-17',
    name: 'Deep Shadows Noir',
    category: 'cinematic',
    description: 'Extreme dark contrast with stylized silhouette emphasis.',
    filterCss: 'contrast(160%) brightness(85%) grayscale(40%)',
  },
  {
    id: 'cine-18',
    name: 'Radiant Sunlight Bloom',
    category: 'cinematic',
    description: 'Bright ethereal lens flare glow and soft contrast.',
    filterCss: 'brightness(115%) contrast(95%) saturate(120%)',
    overlayStyle: {
      background: 'radial-gradient(circle at 80% 20%, rgba(254,240,138,0.2) 0%, transparent 60%)',
    },
  },
  {
    id: 'cine-19',
    name: 'Desaturated Action Grade',
    category: 'cinematic',
    description: 'Gritty muted palette for intense combat scenes.',
    filterCss: 'contrast(130%) saturate(50%) brightness(95%)',
  },
  {
    id: 'cine-20',
    name: 'Neon Magenta Glow',
    category: 'cinematic',
    description: 'Vibrant hot pink and magenta twilight illumination.',
    filterCss: 'contrast(120%) saturate(160%) hue-rotate(240deg)',
  },
  {
    id: 'cine-21',
    name: 'Cinematic Amber Tint',
    category: 'cinematic',
    description: 'Warm rich amber color wash for historical or warm drama.',
    filterCss: 'sepia(45%) contrast(115%) saturate(130%) hue-rotate(-25deg)',
  },
  {
    id: 'cine-22',
    name: 'Midnight Blue Mood',
    category: 'cinematic',
    description: 'Dark blue moonlight nocturnal atmosphere.',
    filterCss: 'contrast(120%) brightness(88%) hue-rotate(170deg) saturate(120%)',
  },
  {
    id: 'cine-23',
    name: 'Silver Screen Classics',
    category: 'cinematic',
    description: 'Smooth grayscale silver tone with subtle shadow glow.',
    filterCss: 'grayscale(100%) contrast(118%) brightness(105%)',
  },
  {
    id: 'cine-24',
    name: 'Velvet Matte Look',
    category: 'cinematic',
    description: 'Lifted black points creating a velvet film finish.',
    filterCss: 'contrast(90%) brightness(108%) saturate(105%)',
    overlayStyle: {
      background: 'rgba(30,27,75,0.08)',
    },
  },
  {
    id: 'cine-25',
    name: 'Cosmic Purple Nebula',
    category: 'cinematic',
    description: 'Deep space purple and violet sci-fi grade.',
    filterCss: 'contrast(125%) saturate(150%) hue-rotate(210deg)',
  },
  {
    id: 'cine-26',
    name: 'Kodachrome 64 Emulation',
    category: 'cinematic',
    description: 'Vibrant primary reds and blues matching classic slide film.',
    filterCss: 'contrast(122%) saturate(145%) brightness(102%)',
  },
  {
    id: 'cine-27',
    name: 'Technicolor 3-Strip',
    category: 'cinematic',
    description: 'Super-saturated classic Golden Era Technicolor print.',
    filterCss: 'contrast(130%) saturate(180%) brightness(104%)',
  },
  {
    id: 'cine-28',
    name: 'Ektachrome Vivid Blue',
    category: 'cinematic',
    description: 'Punchy cool blues and high saturation slide film grade.',
    filterCss: 'contrast(125%) saturate(150%) hue-rotate(15deg)',
  },
  {
    id: 'cine-29',
    name: 'Fuji Chrome Green Gloss',
    category: 'cinematic',
    description: 'Lush natural greens and crisp highlight contrast.',
    filterCss: 'contrast(118%) saturate(135%) hue-rotate(35deg)',
  },
  {
    id: 'cine-30',
    name: 'Infrared Vision Simulation',
    category: 'cinematic',
    description: 'Surreal false-color infrared spectrum look.',
    filterCss: 'invert(80%) hue-rotate(180deg) saturate(200%)',
  },
  {
    id: 'cine-31',
    name: 'Soft Romantic Glow',
    category: 'cinematic',
    description: 'Dreamy soft focus glow with warm highlights.',
    filterCss: 'brightness(108%) contrast(95%) saturate(110%) blur(0.5px)',
    overlayStyle: {
      background: 'rgba(254,205,211,0.1)',
      mixBlendMode: 'screen',
    },
  },
  {
    id: 'cine-32',
    name: 'High Key Bright Commercial',
    category: 'cinematic',
    description: 'Ultra-clean bright commercial aesthetic with soft shadows.',
    filterCss: 'brightness(118%) contrast(98%) saturate(115%)',
  },
  {
    id: 'cine-33',
    name: 'Dramatic Low Key Crime',
    category: 'cinematic',
    description: 'Moody dark shadows with subtle warm highlights.',
    filterCss: 'brightness(82%) contrast(140%) saturate(90%)',
  },
  {
    id: 'cine-34',
    name: 'Urban Street Gritty',
    category: 'cinematic',
    description: 'Edgy high contrast street photography look.',
    filterCss: 'contrast(135%) saturate(85%) brightness(96%)',
  },
  {
    id: 'cine-35',
    name: 'Sepia Cinema Tone',
    category: 'cinematic',
    description: 'Rich dark sepia brown cinema tone.',
    filterCss: 'sepia(70%) contrast(120%) brightness(95%)',
  },
  {
    id: 'cine-36',
    name: 'Cinematic Teal Mono',
    category: 'cinematic',
    description: 'Monochromatic deep teal color grade.',
    filterCss: 'hue-rotate(130%) saturate(130%) contrast(120%)',
  },
  {
    id: 'cine-37',
    name: 'Bronze Gloss Glow',
    category: 'cinematic',
    description: 'Polished metallic bronze highlights and warm contrast.',
    filterCss: 'contrast(125%) sepia(40%) saturate(130%) brightness(103%)',
  },
  {
    id: 'cine-38',
    name: 'Frost Cold Winter',
    category: 'cinematic',
    description: 'Pale icy blue winter landscape grade.',
    filterCss: 'hue-rotate(160%) saturate(70%) brightness(105%) contrast(110%)',
  },
  {
    id: 'cine-39',
    name: 'Crimson Dusk Red',
    category: 'cinematic',
    description: 'Dramatic deep red horizon atmosphere.',
    filterCss: 'hue-rotate(-40%) saturate(160%) contrast(125%)',
  },
  {
    id: 'cine-40',
    name: 'Cinematic Pop Vivid',
    category: 'cinematic',
    description: 'Vibrant colorful contrast pop for modern music videos.',
    filterCss: 'contrast(128%) saturate(165%) brightness(105%)',
  },
  {
    id: 'cine-41',
    name: 'Matte Black Cinema',
    category: 'cinematic',
    description: 'Faded charcoal shadows with high midtone clarity.',
    filterCss: 'contrast(95%) brightness(102%) saturate(95%)',
    overlayStyle: {
      boxShadow: 'inset 0 0 80px rgba(0,0,0,0.5)',
    },
  },
  {
    id: 'cine-42',
    name: 'Anamorphic Gold Streak',
    category: 'cinematic',
    description: 'Warm golden horizontal anamorphic light streaks.',
    filterCss: 'contrast(115%) saturate(125%)',
    overlayStyle: {
      background: 'linear-gradient(180deg, transparent 48%, rgba(245,158,11,0.25) 50%, transparent 52%)',
      mixBlendMode: 'screen',
    },
  },
  {
    id: 'cine-43',
    name: 'Vintage Sepia Gloss',
    category: 'cinematic',
    description: 'Antique sepia photograph with polished gloss contrast.',
    filterCss: 'sepia(80%) contrast(130%) brightness(98%)',
  },
  {
    id: 'cine-44',
    name: 'Cyberpunk Red City',
    category: 'cinematic',
    description: 'Searing neon red and dark shadow grade.',
    filterCss: 'hue-rotate(-50%) saturate(190%) contrast(140%)',
  },
  {
    id: 'cine-45',
    name: 'Emerald Forest Deep',
    category: 'cinematic',
    description: 'Deep organic forest greens and warm shadows.',
    filterCss: 'hue-rotate(50%) saturate(135%) contrast(115%)',
  },
  {
    id: 'cine-46',
    name: 'Golden Sunset Gloss',
    category: 'cinematic',
    description: 'Luminous golden hour sunset glow.',
    filterCss: 'sepia(30%) saturate(150%) contrast(115%) brightness(106%)',
  },
  {
    id: 'cine-47',
    name: 'Bleached Contrast Punch',
    category: 'cinematic',
    description: 'Aggressive bleach bypass with punchy highlights.',
    filterCss: 'contrast(155%) saturate(45%) brightness(104%)',
  },
  {
    id: 'cine-48',
    name: 'Dark Fantasy Mood',
    category: 'cinematic',
    description: 'Mystical dark purple and midnight green grade.',
    filterCss: 'contrast(130%) saturate(120%) hue-rotate(110%) brightness(88%)',
  },
  {
    id: 'cine-49',
    name: 'Vivid Blockbuster Action',
    category: 'cinematic',
    description: 'High dynamic range vivid blockbuster cinema finish.',
    filterCss: 'contrast(135%) saturate(145%) brightness(103%)',
  },
  {
    id: 'cine-50',
    name: 'Cinema Masterpiece',
    category: 'cinematic',
    description: 'Ultimate balanced 35mm theatrical feature film look.',
    filterCss: 'contrast(118%) saturate(122%) brightness(101%)',
    overlayStyle: {
      boxShadow: 'inset 0 0 60px rgba(0,0,0,0.4)',
    },
  },
];
