import { VideoEffect } from './types';

export const RETRO_EFFECTS: VideoEffect[] = [
  {
    id: 'retro-1',
    name: '8mm Home Movie',
    category: 'retro',
    description: 'Vintage 8mm family home video with warm sepia and soft jitter.',
    filterCss: 'sepia(40%) contrast(110%) saturate(120%)',
    getDynamicStyle: (t: number) => ({
      transformCss: `translate(${Math.sin(t * 15) * 1.5}px, ${Math.cos(t * 18) * 1.5}px)`,
    }),
    overlayStyle: {
      background: 'radial-gradient(circle, transparent 60%, rgba(120,50,0,0.3) 100%)',
    },
  },
  {
    id: 'retro-2',
    name: 'VHS Tape Distort',
    category: 'retro',
    description: 'Classic 90s VCR video tape noise and tracking distortion.',
    filterCss: 'contrast(120%) saturate(140%) hue-rotate(-15deg)',
    getDynamicStyle: (t: number) => ({
      transformCss: `translateX(${Math.sin(t * 30) * 3}px)`,
      filterCss: `contrast(120%) saturate(140%) hue-rotate(${Math.sin(t * 20) * 10 - 15}deg)`,
    }),
    overlayStyle: {
      backgroundImage: 'linear-gradient(rgba(255,255,255,0.06) 1px, transparent 1px)',
      backgroundSize: '100% 4px',
    },
  },
  {
    id: 'retro-3',
    name: '16mm Vintage Grain',
    category: 'retro',
    description: 'Classic 16mm indie film stock with textured grain and warm tones.',
    filterCss: 'sepia(25%) contrast(115%) brightness(102%)',
    overlayStyle: {
      boxShadow: 'inset 0 0 70px rgba(0,0,0,0.6)',
    },
  },
  {
    id: 'retro-4',
    name: '1920s Silent Film',
    category: 'retro',
    description: 'Flickering black-and-white early cinema simulation.',
    getDynamicStyle: (t: number) => ({
      filterCss: `grayscale(100%) contrast(150%) brightness(${90 + Math.sin(t * 25) * 15}%)`,
      transformCss: `translate(${Math.sin(t * 35) * 2}px, ${Math.cos(t * 40) * 2}px)`,
    }),
  },
  {
    id: 'retro-5',
    name: 'Sepia Memories',
    category: 'retro',
    description: 'Timeless rich golden sepia historical photograph finish.',
    filterCss: 'sepia(85%) contrast(115%) brightness(96%)',
  },
  {
    id: 'retro-6',
    name: '90s CRT Scanlines',
    category: 'retro',
    description: 'Cathode-ray tube television horizontal scanline grid.',
    filterCss: 'contrast(125%) saturate(130%)',
    overlayStyle: {
      backgroundImage: 'linear-gradient(rgba(0,0,0,0.3) 50%, transparent 50%)',
      backgroundSize: '100% 4px',
    },
  },
  {
    id: 'retro-7',
    name: 'Vintage Camcorder',
    category: 'retro',
    description: 'Handheld family video recording look with tape color noise.',
    filterCss: 'contrast(115%) saturate(125%) hue-rotate(10deg)',
    getDynamicStyle: (t: number) => ({
      transformCss: `translate(${Math.sin(t * 8) * 2}px, ${Math.cos(t * 6) * 2}px)`,
    }),
  },
  {
    id: 'retro-8',
    name: 'Glitch Tape Wobble',
    category: 'retro',
    description: 'Magnetic video tape signal distortion and wobble.',
    getDynamicStyle: (t: number) => ({
      transformCss: `skewX(${Math.sin(t * 12) * 2}deg) scale(1.03)`,
      filterCss: `hue-rotate(${Math.sin(t * 15) * 25}deg)`,
    }),
  },
  {
    id: 'retro-9',
    name: 'Cassette Tape Glow',
    category: 'retro',
    description: 'Retro magnetic tape analog warmth with soft glow.',
    filterCss: 'sepia(35%) saturate(140%) contrast(110%) brightness(105%)',
  },
  {
    id: 'retro-10',
    name: 'Technicolor 1950s',
    category: 'retro',
    description: 'Vivid vintage 1950s Technicolor dye transfer emulation.',
    filterCss: 'contrast(135%) saturate(175%) brightness(103%)',
  },
  {
    id: 'retro-11',
    name: '70s Disco Funk',
    category: 'retro',
    description: 'Groovy warm 1970s color palette with magenta highlights.',
    filterCss: 'sepia(30%) saturate(150%) hue-rotate(-25deg) contrast(115%)',
  },
  {
    id: 'retro-12',
    name: 'Polaroid Instant Film',
    category: 'retro',
    description: 'Instant film aesthetic with faded blacks and rich warm tones.',
    filterCss: 'contrast(105%) brightness(110%) sepia(20%) saturate(115%)',
    overlayStyle: {
      boxShadow: 'inset 0 0 50px rgba(120,60,0,0.3)',
    },
  },
  {
    id: 'retro-13',
    name: 'Super 8 Retro Reel',
    category: 'retro',
    description: 'Classic Super 8 film projector reel look with frame jitter.',
    getDynamicStyle: (t: number) => ({
      transformCss: `translateY(${Math.sin(t * 20) * 2}px) scale(1.03)`,
      filterCss: `sepia(45%) contrast(120%) brightness(${98 + Math.sin(t * 18) * 8}%)`,
    }),
  },
  {
    id: 'retro-14',
    name: 'Disposable Camera',
    category: 'retro',
    description: 'Single-use flash photo camera look with strong saturation.',
    filterCss: 'contrast(130%) brightness(108%) saturate(140%)',
  },
  {
    id: 'retro-15',
    name: 'Arcade 8-Bit Vibe',
    category: 'retro',
    description: 'Retro gaming arcade cabinet aesthetic.',
    filterCss: 'contrast(140%) saturate(180%) hue-rotate(50deg)',
    overlayStyle: {
      backgroundImage: 'radial-gradient(rgba(0,0,0,0.2) 1px, transparent 0)',
      backgroundSize: '4px 4px',
    },
  },
  {
    id: 'retro-16',
    name: 'Lo-Fi VCR Distortion',
    category: 'retro',
    description: 'Lo-fi analog cassette tape distortion with color bleeds.',
    getDynamicStyle: (t: number) => ({
      transformCss: `translateX(${Math.cos(t * 22) * 4}px)`,
      filterCss: `contrast(125%) saturate(135%) hue-rotate(${Math.cos(t * 12) * 15}deg)`,
    }),
  },
  {
    id: 'retro-17',
    name: 'Analog TV Static',
    category: 'retro',
    description: 'Broadcast television snow signal static overlay.',
    filterCss: 'contrast(130%) saturate(120%)',
    overlayStyle: {
      background: 'rgba(255,255,255,0.06)',
      mixBlendMode: 'difference',
    },
  },
  {
    id: 'retro-18',
    name: 'Dust & Scratch Antique',
    category: 'retro',
    description: 'Aged archival film with dust and scratch vignette.',
    filterCss: 'sepia(50%) contrast(125%) brightness(95%)',
    overlayStyle: {
      boxShadow: 'inset 0 0 90px rgba(0,0,0,0.7)',
    },
  },
  {
    id: 'retro-19',
    name: 'Damaged Tape Roll',
    category: 'retro',
    description: 'Crinkled magnetic tape reel with periodic jumping lines.',
    getDynamicStyle: (t: number) => ({
      transformCss: `translateY(${(t % 1 < 0.08 ? -8 : 0)}px)`,
      filterCss: `contrast(130%) saturate(120%)`,
    }),
  },
  {
    id: 'retro-20',
    name: 'Retro Glitch Strobe',
    category: 'retro',
    description: 'High-speed analog strobe glitch.',
    getDynamicStyle: (t: number) => ({
      filterCss: `invert(${t % 0.4 < 0.06 ? 40 : 0}%) contrast(135%)`,
    }),
  },
  {
    id: 'retro-21',
    name: 'Monochromatic Sepia',
    category: 'retro',
    description: 'Pure single-tone deep sepia brown photo.',
    filterCss: 'grayscale(100%) sepia(100%) contrast(120%)',
  },
  {
    id: 'retro-22',
    name: 'Vintage Newspaper Print',
    category: 'retro',
    description: 'Halftone dot printed newsprint aesthetic.',
    filterCss: 'grayscale(100%) contrast(160%) brightness(105%)',
  },
  {
    id: 'retro-23',
    name: '80s Synthwave Glow',
    category: 'retro',
    description: 'Neon retro-futuristic 1980s synthwave color palette.',
    filterCss: 'contrast(135%) saturate(170%) hue-rotate(200deg)',
    overlayStyle: {
      background: 'linear-gradient(to bottom, rgba(236,72,153,0.12), rgba(139,92,246,0.12))',
    },
  },
  {
    id: 'retro-24',
    name: 'Retro Vignette Border',
    category: 'retro',
    description: 'Heavy rounded vintage corner vignette shadow.',
    filterCss: 'sepia(30%) contrast(115%)',
    overlayStyle: {
      boxShadow: 'inset 0 0 110px rgba(0,0,0,0.85)',
    },
  },
  {
    id: 'retro-25',
    name: 'Old Projector Flicker',
    category: 'retro',
    description: 'Mechanical film bulb intensity flickering.',
    getDynamicStyle: (t: number) => ({
      filterCss: `sepia(35%) contrast(118%) brightness(${95 + Math.sin(t * 30) * 12}%)`,
    }),
  },
  {
    id: 'retro-26',
    name: 'VHS Tracking Errors',
    category: 'retro',
    description: 'Misaligned VCR tracking band at bottom of video.',
    filterCss: 'contrast(120%) saturate(130%)',
    overlayStyle: {
      background: 'linear-gradient(to top, rgba(255,255,255,0.2) 0%, transparent 10%)',
    },
  },
  {
    id: 'retro-27',
    name: 'Retro Color Shift',
    category: 'retro',
    description: 'Dynamic hue cycling vintage color distortion.',
    getDynamicStyle: (t: number) => ({
      filterCss: `hue-rotate(${Math.sin(t * 2) * 40}deg) contrast(115%) saturate(130%)`,
    }),
  },
  {
    id: 'retro-28',
    name: 'Faded Photo 1960s',
    category: 'retro',
    description: 'Soft sun-bleached 1960s print photograph look.',
    filterCss: 'contrast(90%) brightness(112%) sepia(30%) saturate(85%)',
  },
  {
    id: 'retro-29',
    name: 'Vinyl Groove Vibe',
    category: 'retro',
    description: 'Warm analog record sleeve color warmth.',
    filterCss: 'sepia(45%) contrast(112%) saturate(125%) brightness(98%)',
  },
  {
    id: 'retro-30',
    name: 'Saturated VHS Strobe',
    category: 'retro',
    description: 'Intense saturated VCR color popping.',
    filterCss: 'contrast(140%) saturate(200%) hue-rotate(-10deg)',
  },
  {
    id: 'retro-31',
    name: 'B&W Silent Movie Scratches',
    category: 'retro',
    description: 'Early 1900s monochrome film with vertical scratch lines.',
    getDynamicStyle: (t: number) => ({
      filterCss: `grayscale(100%) contrast(140%) brightness(${92 + Math.sin(t * 22) * 10}%)`,
    }),
    overlayStyle: {
      backgroundImage: 'linear-gradient(90deg, transparent 49%, rgba(255,255,255,0.15) 50%, transparent 51%)',
      backgroundSize: '40px 100%',
    },
  },
  {
    id: 'retro-32',
    name: 'Retro Magenta Wash',
    category: 'retro',
    description: 'Vintage degraded film stock magenta hue shift.',
    filterCss: 'contrast(115%) saturate(135%) hue-rotate(-40deg) sepia(20%)',
  },
  {
    id: 'retro-33',
    name: 'Early Color Film 1930s',
    category: 'retro',
    description: 'Primitive two-color film process look.',
    filterCss: 'sepia(50%) hue-rotate(-20deg) contrast(125%) saturate(140%)',
  },
  {
    id: 'retro-34',
    name: 'CRT Pixel Grid',
    category: 'retro',
    description: 'Close-up RGB cathode ray tube subpixel grid texture.',
    filterCss: 'contrast(130%) saturate(150%)',
    overlayStyle: {
      backgroundImage: 'radial-gradient(rgba(255,255,255,0.15) 1px, transparent 1px)',
      backgroundSize: '3px 3px',
    },
  },
  {
    id: 'retro-35',
    name: 'Retro Film Roll Burn',
    category: 'retro',
    description: 'Solarized edge burn from light leakage on film roll.',
    filterCss: 'contrast(125%) saturate(140%) sepia(35%)',
    overlayStyle: {
      background: 'radial-gradient(circle at 10% 50%, rgba(245,158,11,0.3) 0%, transparent 50%)',
    },
  },
  {
    id: 'retro-36',
    name: 'Sepia Vignette Gloss',
    category: 'retro',
    description: 'Polished sepia tone with dark oval framing.',
    filterCss: 'sepia(65%) contrast(125%) brightness(96%)',
    overlayStyle: {
      boxShadow: 'inset 0 0 100px rgba(80,40,0,0.85)',
    },
  },
  {
    id: 'retro-37',
    name: 'Low FPS Vintage Trot',
    category: 'retro',
    description: 'Stepping motion style simulating 12 FPS hand-cranked film.',
    filterCss: 'sepia(35%) contrast(120%)',
  },
  {
    id: 'retro-38',
    name: 'Retro Neon Distortion',
    category: 'retro',
    description: 'Electric 1980s neon tube color distortion.',
    filterCss: 'contrast(140%) saturate(180%) hue-rotate(120deg)',
  },
  {
    id: 'retro-39',
    name: 'Vintage Magenta Hue',
    category: 'retro',
    description: 'Deep faded magenta photograph tone.',
    filterCss: 'sepia(25%) hue-rotate(-30deg) saturate(145%) contrast(118%)',
  },
  {
    id: 'retro-40',
    name: 'Retro Blue Phosphor',
    category: 'retro',
    description: 'Blue phosphor monitor screen display emulation.',
    filterCss: 'grayscale(80%) hue-rotate(180deg) saturate(180%) contrast(130%)',
  },
  {
    id: 'retro-41',
    name: 'Faded Sepia Print',
    category: 'retro',
    description: 'Subtle faded sepia paper photograph look.',
    filterCss: 'sepia(50%) contrast(98%) brightness(106%) saturate(90%)',
  },
  {
    id: 'retro-42',
    name: '1980s VHS Playback',
    category: 'retro',
    description: 'Standard home VCR video tape playback look.',
    filterCss: 'contrast(115%) saturate(135%) hue-rotate(5deg)',
    overlayStyle: {
      backgroundImage: 'linear-gradient(rgba(255,255,255,0.05) 1px, transparent 1px)',
      backgroundSize: '100% 3px',
    },
  },
  {
    id: 'retro-43',
    name: 'Retro Amber Glow',
    category: 'retro',
    description: 'Warm glowing amber computer terminal display.',
    filterCss: 'sepia(90%) saturate(200%) hue-rotate(-20deg) contrast(125%)',
  },
  {
    id: 'retro-44',
    name: 'Old Cinema Projector',
    category: 'retro',
    description: 'Theatrical 35mm carbon arc lamp projector glow.',
    getDynamicStyle: (t: number) => ({
      filterCss: `sepia(30%) contrast(120%) brightness(${98 + Math.sin(t * 24) * 8}%)`,
    }),
  },
  {
    id: 'retro-45',
    name: 'Glitchy Scanline Roll',
    category: 'retro',
    description: 'Rolling vertical sync TV scanline glitch.',
    getDynamicStyle: (t: number) => ({
      transformCss: `translateY(${(Math.sin(t * 5) * 5)}px)`,
      filterCss: `contrast(125%) saturate(130%)`,
    }),
  },
  {
    id: 'retro-46',
    name: 'Damaged Film Edge',
    category: 'retro',
    description: 'Sprocket hole shadow distortion along film edge.',
    filterCss: 'sepia(40%) contrast(120%)',
    overlayStyle: {
      boxShadow: 'inset 25px 0 20px -10px rgba(0,0,0,0.8), inset -25px 0 20px -10px rgba(0,0,0,0.8)',
    },
  },
  {
    id: 'retro-47',
    name: 'Retro Pop Art',
    category: 'retro',
    description: 'High-contrast 1960s pop art color saturation.',
    filterCss: 'contrast(160%) saturate(220%) hue-rotate(60deg)',
  },
  {
    id: 'retro-48',
    name: 'Vintage Warm Glow',
    category: 'retro',
    description: 'Soft warm nostalgic sunlight glow on vintage lens.',
    filterCss: 'sepia(35%) brightness(108%) saturate(125%) contrast(108%)',
  },
  {
    id: 'retro-49',
    name: 'Sepia Film Scratch',
    category: 'retro',
    description: 'Sepia tone video with random optical scratches.',
    getDynamicStyle: (t: number) => ({
      filterCss: `sepia(75%) contrast(125%) brightness(${96 + (Math.random() < 0.1 ? -10 : 0)}%)`,
    }),
  },
  {
    id: 'retro-50',
    name: 'Classic Retro Master',
    category: 'retro',
    description: 'Ultimate master retro effect combining analog tape and sepia film.',
    filterCss: 'sepia(45%) contrast(122%) saturate(130%) brightness(101%)',
    overlayStyle: {
      boxShadow: 'inset 0 0 80px rgba(0,0,0,0.6)',
      backgroundImage: 'linear-gradient(rgba(255,255,255,0.04) 1px, transparent 1px)',
      backgroundSize: '100% 3px',
    },
  },
];
